name: MultiUHC
version: 1.3
author: CyZeTLC
main: de.cyzetlc.Main

commands:
   setspawn:
      description: Dieser Command kann alle Spawns verwalten.
   kit:
      description: Dieser Command kann die Kits einstellen.
   stats:
      description: Dieser Command zeigt Spieler Stats an.
   to:
   sz:
   start:
   build:
   ec:
   backpack:
   bp:
   